- setup:

- name: Install kubectl
  apt:
    name:
      - kubectl
    state: present

- name: Hold kubectl at current version
  command: apt-mark hold kubectl

# 10.0 is used here because we used the same range in terraform - change with that in mind # until i make this a variable (:
- name: set Internal IP
  set_fact:
    internal_ip: "{{ (ansible_all_ipv4_addresses | select('search', '10\\.0') | list).0 }}"

- name: print init command
  debug:
    msg: "kubeadm init --control-plane-endpoint={{ internal_ip }} --apiserver-advertise-address={{ internal_ip }} --pod-network-cidr=192.168.0.0/16 --cri-socket=unix:///run/containerd/containerd.sock"

- name: run init command
  command: "kubeadm init --control-plane-endpoint={{ internal_ip }} --apiserver-advertise-address={{ internal_ip }} --pod-network-cidr=192.168.0.0/16 --cri-socket=unix:///run/containerd/containerd.sock"
  register: init_output
  run_once: true

- debug:
    msg: "{{ init_output.stdout_lines }}"
